name: AuCore IG publish

on:
  push:
    branches: [ "feature/cicd" ]
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: hl7fhir/ig-publisher-base    # use ig publisher base image
    steps:
    - name: Checkout AU Core Repository
      uses: actions/checkout@v4

    - name: Update Publisher
      run: |
        _updatePublisher.sh -f -y

    # - name: Basic Publisher build
    #   run: |
    #     _genonce.sh

    - name: Run Complex Publisher build
      run: java -jar input-cache/publisher.jar -ig ig.ini -publish -target https://build.fhir.org.au/ig/hl7au/au-fhir-core/branches/example
# java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because the return value of "org.hl7.fhir.igtools.publisher.Publisher.targetUrl()" is null
      # might require -nested since publisher.java has self.targetOutputNested = CliParams.getNamedParam(args, "-nested");

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ig-output
        path: output/full-ig.zip # full ig zip is 1/10 the size but has all relevant content?

    # - name: 📂 Sync files
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
    #   with:
    #     server: ${{secrets.BUILD_SERVER}} # change to be env variable to support multiple environments later on
    #     username: ${{ secrets.FTP_USER }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     local-dir: output/
    #     server-dir: /ig/hl7au/au-fhir-core/branches/${{ github.ref }}/publish/
        # dry-run: true