name: AU Core fhir.org.au IG Publisher CI Build

on:
  push:
    branches: [ "feature/cicd" ]
  pull_request:
    branches: [ "feature/cicd" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: hl7fhir/ig-publisher-base    # use ig publisher base image
    steps:
    - name: Checkout AU Core Repository
      uses: actions/checkout@v4

    # - name: Run JAR File
    #   run: java -jar input-cache/publisher.jar -ig ig.ini  

    - name: Build IG 
      run: |
        _updatePublisher.sh -f -y
        _genonce.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ig-output
        path: output/

    # - name: FTP to Server
    #   run: |
    #     ftp-upload-command --host ${{build.fhir.org.au}} --user ${{ secrets.FTP_USER }} --password ${{ secrets.FTP_PASSWORD }} output/
